# 5.12. Trying the Julia programming language in the Jupyter Notebook

In [1]:
println("Hello world!")

Hello world!


In [2]:
f(z, c) = z.*z .+ c

f (generic function with 1 method)

In [3]:
f(2.0 + 1.0im, 1.0)

4.0 + 4.0im

In [4]:
z = [-1.0 - 1.0im  1.0 - 1.0im;
     -1.0 + 1.0im  1.0 + 1.0im]

2×2 Array{Complex{Float64},2}:
 -1.0-1.0im  1.0-1.0im
 -1.0+1.0im  1.0+1.0im

In [5]:
z[1,end]

1.0 - 1.0im

In [6]:
f(z, 0)

2×2 Array{Complex{Float64},2}:
 0.0+2.0im  0.0-2.0im
 0.0-2.0im  0.0+2.0im

In [7]:
function julia(z, c; maxiter=200)
    for n = 1:maxiter
        if abs2(z) > 4.0
            return n-1
        end
        z = f(z, c)
    end
    return maxiter
end

julia (generic function with 1 method)

In [10]:
import Pkg
Pkg.add("PyCall")
using PyCall

  Updating registry at `/usr/local/software/jureca/Stages/Devel-2019a/software/Jupyter/2019a-rc30-gcccoremkl-8.3.0-2019.3.199-Python-3.6.8/share/julia/site/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 %12.3 %>                              ]  24.7 %>                       ]  41.0 %======================>                  ]  53.3 %]  65.6 %          ]  73.2 % [===================================>     ]  85.6 %Fetching: [======================================>  ]  93.4 % Resolving package versions...
 Installed OrderedCollections ─ v1.1.0
 Installed MacroTools ───────── v0.5.3
 Installed PyCall ───────────── v1.91.2
 Installed DataStructures ───── v0.17.7
  Updating `/usr/local/software/jureca/Stages/Devel-2019a/software/Jupyter/2019a-rc30-gcccoremkl-8.3.0-2019.3.199-Python-3.6.8/share/julia/site/environments/v1.1/Project.toml`
  [438e738f] + PyCall v1.91.2
  Updating `/usr/local/s

┌ Info: Precompiling PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]
└ @ Base loading.jl:1186


In [13]:
@pyimport numpy as np

In [14]:
z = np.linspace(-1., 1., 100)

100-element Array{Float64,1}:
 -1.0               
 -0.9797979797979798
 -0.9595959595959596
 -0.9393939393939394
 -0.9191919191919192
 -0.898989898989899 
 -0.8787878787878788
 -0.8585858585858586
 -0.8383838383838383
 -0.8181818181818181
 -0.797979797979798 
 -0.7777777777777778
 -0.7575757575757576
  ⋮                 
  0.7777777777777779
  0.7979797979797982
  0.8181818181818183
  0.8383838383838385
  0.8585858585858588
  0.8787878787878789
  0.8989898989898992
  0.9191919191919193
  0.9393939393939394
  0.9595959595959598
  0.9797979797979799
  1.0               

In [15]:
m = [julia(z[i], 0.5) for i=1:100]

100-element Array{Int64,1}:
 2
 2
 2
 2
 2
 2
 2
 2
 3
 3
 3
 3
 3
 ⋮
 3
 3
 3
 3
 2
 2
 2
 2
 2
 2
 2
 2

In [18]:
@time m = [julia(complex(r, i), complex(-0.06, 0.67))
           for i = 1:-.001:-1,
               r = -1.5:.001:1.5];

  1.217659 seconds (736.41 k allocations: 82.496 MiB, 4.63% gc time)
